on: [push]

jobs:
  eslint-reporter:
    runs-on: ubuntu-latest
    name: Example ESLint Reporter Usage
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ESLint Report
        if: always()
        uses: ./
        with:
          json: ./sample.json
          title: ESLint Report
